# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isfavorite',
            field=models.BooleanField(default=False),
        ),
    ]
