# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_albumlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumLogo',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
